name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci
        
    - name: Build backend
      run: npm run build --prefix api

    - name: Build bot
      run: dotnet build api/extensions.csproj --configuration Release --output api/bin

    - name: Deploy backend to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: demo
        package: api
        publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}

    - name: Deploy bot to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: demo
        publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
        package: bot
      
    - name: Build frontend
      run: npm run build --prefix tabs

    - name: Deploy frontend to Azure Storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob upload-batch --destination '$web' --source ./tabs/build --account-name <YOUR_AZURE_STORAGE_ACCOUNT_NAME>  --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
